routes/web.php
<?php

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\AnswerController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PDFController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('auth/github', [AuthController::class,'redirectToProvider'])->name('login.github');
Route::get('auth/github/callback', [AuthController::class,'handleProviderCallback']);

Route::resource('question', QuestionController::class);
Route::prefix('question/{question}')->group(function () {
    Route::resource('answer', AnswerController::class, [
        'except' => ['show', 'index']
    ])->middleware('auth');
    Route::post('/answer/{answer}/approve', [AnswerController::class, 'approve'])->name('answer.approve')->middleware('auth');
    Route::put('/answer/{answer}/unapprove', [AnswerController::class, 'unapprove'])->name('answer.unapprove')->middleware('auth');
    Route::post('/generatepdf',[PDFController::class,'question'])->name('question.generatepdf');
});

Route::resource('tag', TagController::class, [
    'only' => ['index', 'store', 'destroy']
]);

Route::get('/tag/{tag}/question',[TagController::class,'question'])->name('tag.question');
Route::get('/tag/{tag}/article',[TagController::class,'article'])->name('tag.article');

Route::get('/', [HomeController::class,'index'] )->name('home');
Route::post('/searchTag',[HomeController::class,'searchTag'])->name('tag.search');


Route::prefix('comment')->group(function () {
    Route::get('{question}/create', [CommentController::class, 'commentQuestionCreate'])->name('commentQuestion.create');
    Route::get('answer/{answer}/create', [CommentController::class, 'commentAnswerCreate'])->name('commentAnswer.create');
    Route::post('{question}', [CommentController::class, 'commentQuestionStore'])->name('commentQuestion.store');
    Route::post('answer/{answer}', [CommentController::class, 'commentAnswerStore'])->name('commentAnswer.store');
    Route::delete('{comment}', [CommentController::class, 'destroy'])->name('comment.destroy');
});

Route::resource('user', UserController::class,[
        
]);
Route::resource('article',ArticleController::class);

Route::prefix('article')->group(function(){
    Route::get('{article}/comment/create',[CommentController::class,'commentArticleCreate'])->name('commentArticle.create');
    Route::post('{article}/comment',[CommentController::class,'commentArticleStore'])->name('commentArticle.store');
});

Route::get('user/{user}/article', [ArticleController::class, 'userArticle'])->name('user.article');
Route::get('user/{user}/dashboard', [UserController::class,'dashboard'])->name('dashboard');
Route::get('user/{user}/verify',[UserController::class,'verify'])->name('user.verify');
Route::get('user/{user}/notification', [NotificationController::class,'index'])->name('user.notification');
Route::get('user/{user}/notification/{notification}', [NotificationController::class,'show'])->name('notification.show');

Route::view('/test', 'pdf.question');

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function tags(){
        return $this->belongsToMany(Tag::class);
    }

    public function answers(){
        return $this->hasMany(Answer::class);
    }
    
    public function comments(){
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Answer;
use App\Models\Question;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Tag;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware(['auth','verified'])->except([
            'index', 'show'
        ]);
        $this->middleware('question.maker')->only([
            'edit', 'update', 'destroy'
        ]);
    }
    public function index()
    {
        $questions = Question::orderBy('id', 'DESC')->paginate(10);
        // dd($questions);  
        return view('question.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::orderBy('name', 'asc')->get();
        return view('question.create', compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);        
        $question = Question::create([
            'title' => $request->title,
            'text' => $request->text,
            'user_id' => Auth::id(),
        ]);
        $tags = $request->tag;
        if (!empty($tags)) {
            foreach ($tags as $tagName) {
                $tag = Tag::firstOrCreate([
                    'name' => $tagName,
                ]);
                if ($tag) {
                    $tagNames[] = $tag->id;
                }
            }
            $question->tags()->syncWithoutDetaching($tagNames);
        }
        return redirect(route('question.index'))->with('toast_success', 'Pertanyaan berhasil diinput');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {        
        $answers = Answer::where('question_id', $question->id)
            ->orderBy('created_at', 'DESC')
            ->get();        
        return view('question.show', compact('question', 'answers'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        return view('question.edit', compact('question'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question)
    {
        Question::where('id', $question->id)->update([
            'title' => $request->title,
            'text' => $request->text,
        ]);
        return redirect(route('question.show', ['question' => $question]))->with('toast_info', 'Pertanyaan berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        Question::destroy($question->id);
        return redirect(route('question.index'))->with('toast_success', 'Pertanyaan berhasil didelete');
    }
}

resources/views/question/create.blade.php
@extends('layouts.base')

@section('title')
    <title>SN - Create</title>
@endsection

@section('css')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endsection

@section('js')
    <script src="https://cdn.tiny.cloud/1/{{ env('TINY_API') }}/tinymce/5/tinymce.min.js"
        referrerpolicy="origin"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js" defer></script>

@endsection
@section('content')
    <h2 class="text-gray-700">
        Create Question
    </h2>
    <hr class="">
    <div class="col-md-12">
        <form action="{{ route('question.store') }}" method="post">
            @csrf
            <label for="title" class="col-form-label text-gray-700">Title</label>
            <input type="text" name="title" id="title" class="form-control" required>
            <label for="content" class="col-form-label text-gray-700">Text</label>
            <textarea name="text" id="text" cols="30" rows="10"></textarea>
            <label for="tags" class="col-form-label">Tags</label>
            <select class="form-control select2 select-tags" name="tag[]" id="tags" multiple>
                @foreach ($tags as $tag)
                    <option value="{{ $tag->name }}">{{ $tag->name }}</option>
                @endforeach
            </select>
            <small id="tagsHelp" class="form-text text-muted">Separate ur tags using comma ( , )</small>

            <div class="my-4">
                <button type="submit" class="btn btn-primary mr-auto"> Submit <i
                        class="fas fa-arrow-alt-circle-right ml-2"></i></button>
            </div>

        </form>
    </div>
@endsection

@push('scripts')
    <script>
        tinymce.init({
            selector: '#text',
            plugins: 'a11ychecker advcode casechange linkchecker autolink lists checklist permanentpen powerpaste table advtable  tinymcespellchecker',
            toolbar: 'a11ycheck casechange checklist code permanentpen table',
            toolbar_mode: 'floating',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
        });

    </script>
@endpush

@push('scripts')
    <script>
        $(function() {
            $(".select-tags").select2({
                placeholder: "Enter tags",
                tags: true,
                tokenSeparators: [',']
            });
        });

    </script>
@endpush

resources/views/question/edit.blade.php
@extends('layouts.base')
@section('title')
    <title>SN - Edit</title>
@endsection
@section('js')
    <script src="https://cdn.tiny.cloud/1/{{ env('TINY_API') }}/tinymce/5/tinymce.min.js" referrerpolicy="origin">
    </script>

@endsection
@section('content')
    <h2 class="text-gray-700">
        Edit Question
    </h2>
    <hr class="">
    <div class="col-md-12">
        <form action="{{ route('question.update', ['question' => $question]) }}" method="post">
            @csrf
            @method('PUT')
            <label for="title" class="col-form-label text-gray-700">Title</label>
            <input type="text" name="title" id="title" class="form-control" required value="{{ $question->title }}">
            <label for="content" class="col-form-label text-gray-700">Text</label>
            <textarea name="text" id="text" cols="30" rows="10">
                    {{ $question->text }}
                </textarea>
            <div class="my-4">
                <button type="submit" onclick="return confirm('Yakin ingin mengedit pertanyaan ini?')"
                    class="btn btn-primary mr-auto"><i class="fas fa-upload"> Update</i></button>
                <input type="reset" value="Reset" class="btn btn-secondary">
            </div>
        </form>
    </div>
@endsection
@push('scripts')
    <script>
        tinymce.init({
            selector: '#text',
            plugins: 'a11ychecker advcode casechange linkchecker autolink lists checklist permanentpen powerpaste table advtable  tinymcespellchecker',
            toolbar: 'a11ycheck casechange checklist code permanentpen table',
            toolbar_mode: 'floating',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
        });

    </script>
@endpush

resources/views/question/index.blade.php
@extends('layouts.base')
@section('title')
    <title>SN - Questions</title>
@endsection
@section('content')
<div class="row justify-content-between">
    <div class="col">
        <h2 class="text-gray-700">
            All Question
        </h2>
    </div>   
    <div class="col">
        <a href="{{ route('question.create') }}" class="btn btn-success float-right mr-3"> <i class="fas fa-plus">  Create</i></a>
    </div>     
</div>    
    <hr>
    <div class="col-md-12">
        @foreach ($questions as $question)
        <div class="card shadow mb-2">
            <div class="card-header">
                #{{ $question->id }}
            </div>
            <div class="card-body">
              <h5 class="card-title text-primary font-weight-bold">{{ $question->title }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">Made by: <a href="{{ route('user.show',['user'=>$question->user]) }}"> {{ $question->user->name }} </a> on {{ $question->created_at }}</h6>
              <div class="card-text text-gray-900">{!! Str::words($question->text, 50, $end=' ...')   !!}</div>
              @foreach ($question->tags as $tag)
              <a href="{{ route('tag.question',['tag' =>$tag]) }}" class="btn btn-primary my-1">{{ $tag->name  }}</a>
              @endforeach                            
            </div>
            <div class="card-footer">
                <a href="{{ route('question.show',['question' => $question]) }}" class="card-link">Show Detail</a>              
            </div>
          </div>
        @endforeach
        {{ $questions->links() }}        
    </div>    
@endsection

resources/views/question/show.blade.php
@extends('layouts.base')
@section('title')
    <title>Details Questione</title>
@endsection
@section('js')
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@endsection
@section('content')
    <h2>Details Questione #{{ $question->id }}</h2>
    <hr>
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col">
                    <h3 class="text-lg">Made by: <a href="{{ route('user.show',['user'=>$question->user]) }}"> {{ $question->user->name }} </a>on {{ $question->created_at }}</h3>
                </div>
                <div class="col">
                    <form action="{{ route('question.generatepdf',['question'=> $question]) }}" method="post" class="form-inline float-right">
                        @csrf
                        <button type="submit" class="btn btn-secondary mr-3" > Export <i class="fa fa-file-pdf ml-2"></i></button>
                        <a href="{{ route('answer.create', ['question' => $question]) }}"
                            class="btn btn-success float-md-right">
                            <i class="fas fa-reply">
                                Answer
                            </i>
                        </a>                    
                    </form>                                        
                </div>
            </div>
        </div>
        <div class="card-body">
            <h3 class="card-title text-primary">{{ $question->title }}</h5>
                <div class="card-text text-gray-900" style="font-size: 20px">{!! $question->text !!}</div>
                @foreach ($question->tags as $tag)
                    <a href="{{ route('tag.question', ['tag' => $tag]) }}"
                        class="btn btn-primary round my-1" style="font-size: 70%">{{ $tag->name }}</a>
                @endforeach
        </div>
        <div class="card-footer">
            <div class="form-group">
                <div class="row">
                    <div class="col-md-9">                        
                        <div class="form-group form-inline">
                            <button class="btn btn-primary w-75 mr-3" type="button" data-toggle="collapse"
                                data-target="#collapseComment" aria-expanded="false" aria-controls="collapseComment">
                                Show Comments ({{ $question->comments->count() }})
                            </button>
                            <a href="{{ route('commentQuestion.create', ['question' => $question]) }}"
                                class="btn btn-success w-auto mt-auto">Add Comment</a>
                        </div>
                        <div class="collapse" id="collapseComment">
                            <div class="card card-body">
                                @foreach ($question->comments as $comment)
                                    <div class="row">
                                        <div class="col-sm-10">

                                            <p style="padding: 0px; margin: 0px">{{ $comment->text }} - <a class="card-link"
                                                    href="{{ route('user.show',['user' => $comment->user]) }}">{{ $comment->user->name }}</a></p>
                                            <p style="padding: 0px; margin: 0px" class="text-gray-500">
                                                {{ $comment->created_at }}</p>
                                            <hr style="padding: 0px; margin: 0px">
                                        </div>
                                        <div class="col">
                                            @if (Auth::id() == $comment->user_id || Auth::user()->role->name == 'admin' )
                                                <a href="{{ route('comment.destroy', ['comment' => $comment]) }}"
                                                    class="btn btn-danger"
                                                    data-target="#deleteQuestionCommentModal{{ $comment->id }}"
                                                    data-toggle="modal">
                                                    <i class="fas fa-trash"></i> Delete</a>
                                                <!-- Delete Question Comment Modal-->
                                                <div class="modal fade" id="deleteQuestionCommentModal{{ $comment->id }}"
                                                    tabindex="0" role="dialog" aria-labelledby="exampleModalLabel"
                                                    aria-hidden="true">
                                                    <div class="modal-dialog" role="document">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title" id="exampleModalLabel">
                                                                    {{ __('Are you Sure want tu delete this Comment') }}
                                                                </h5>
                                                                <button class="close" type="button" data-dismiss="modal"
                                                                    aria-label="Close">
                                                                    <span aria-hidden="true">×</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">{{ 'deleted data is irreversible' }}
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button class="btn btn-link" type="button"
                                                                    data-dismiss="modal">{{ __('Cancel') }}</button>
                                                                <a class="btn btn-danger"
                                                                    href="{{ route('comment.destroy', ['comment' => $comment]) }}"
                                                                    onclick="event.preventDefault(); document.getElementById('delete-question-comment-form-{{ $comment->id }}').submit();">{{ __('Delete') }}</a>
                                                                <form
                                                                    id="delete-question-comment-form-{{ $comment->id }}"
                                                                    action="{{ route('comment.destroy', ['comment' => $comment]) }}"
                                                                    method="POST" style="display: none;">
                                                                    @csrf
                                                                    @method('delete')
                                                                </form>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            @endif
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        @auth
                            @if (Auth::id() == $question->user_id || Auth::user()->role->name == 'admin')
                                <a href="{{ route('question.edit', ['question' => $question]) }}"
                                    class="btn btn-info float-md-right"><i class="fa fa-edit"> Edit</i></a>
                                <a href="{{ route('question.destroy', ['question' => $question]) }}"
                                    class="btn btn-danger float-md-right mr-lg-2" data-toggle="modal"
                                    data-target="#deleteModal">
                                    <i class="fa fa-trash-alt">&nbsp; Delete</i>
                                </a>
                                <!-- Delete Modal-->
                                <div class="modal fade" id="deleteModal" tabindex="0" role="dialog"
                                    aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">{{ __('Are you sure?') }}</h5>
                                                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">×</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">{{ 'deleted data is irreversible' }}</div>
                                            <div class="modal-footer">
                                                <button class="btn btn-link" type="button"
                                                    data-dismiss="modal">{{ __('Cancel') }}</button>
                                                <a class="btn btn-danger"
                                                    href="{{ route('question.destroy', ['question' => $question]) }}"
                                                    onclick="event.preventDefault(); document.getElementById('delete-question-form').submit();">{{ __('Delete') }}</a>
                                                <form id="delete-question-form"
                                                    action="{{ route('question.destroy', ['question' => $question]) }}"
                                                    method="POST" style="display: none;">
                                                    @csrf
                                                    @method('delete')
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endif
                        @endauth
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <h4>Answer Count : {{ count($answers) }}</h4>
    @foreach ($answers as $answer)
        @include('components.answer',['answer' => $answer,'question' =>$question])
    @endforeach
@endsection