routes/web.php
<?php

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\AnswerController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PDFController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('auth/github', [AuthController::class,'redirectToProvider'])->name('login.github');
Route::get('auth/github/callback', [AuthController::class,'handleProviderCallback']);

Route::resource('question', QuestionController::class);
Route::prefix('question/{question}')->group(function () {
    Route::resource('answer', AnswerController::class, [
        'except' => ['show', 'index']
    ])->middleware('auth');
    Route::post('/answer/{answer}/approve', [AnswerController::class, 'approve'])->name('answer.approve')->middleware('auth');
    Route::put('/answer/{answer}/unapprove', [AnswerController::class, 'unapprove'])->name('answer.unapprove')->middleware('auth');
    Route::post('/generatepdf',[PDFController::class,'question'])->name('question.generatepdf');
});

Route::resource('tag', TagController::class, [
    'only' => ['index', 'store', 'destroy']
]);

Route::get('/tag/{tag}/question',[TagController::class,'question'])->name('tag.question');
Route::get('/tag/{tag}/article',[TagController::class,'article'])->name('tag.article');

Route::get('/', [HomeController::class,'index'] )->name('home');
Route::post('/searchTag',[HomeController::class,'searchTag'])->name('tag.search');


Route::prefix('comment')->group(function () {
    Route::get('{question}/create', [CommentController::class, 'commentQuestionCreate'])->name('commentQuestion.create');
    Route::get('answer/{answer}/create', [CommentController::class, 'commentAnswerCreate'])->name('commentAnswer.create');
    Route::post('{question}', [CommentController::class, 'commentQuestionStore'])->name('commentQuestion.store');
    Route::post('answer/{answer}', [CommentController::class, 'commentAnswerStore'])->name('commentAnswer.store');
    Route::delete('{comment}', [CommentController::class, 'destroy'])->name('comment.destroy');
});

Route::resource('user', UserController::class,[
        
]);
Route::resource('article',ArticleController::class);

Route::prefix('article')->group(function(){
    Route::get('{article}/comment/create',[CommentController::class,'commentArticleCreate'])->name('commentArticle.create');
    Route::post('{article}/comment',[CommentController::class,'commentArticleStore'])->name('commentArticle.store');
});

Route::get('user/{user}/article', [ArticleController::class, 'userArticle'])->name('user.article');
Route::get('user/{user}/dashboard', [UserController::class,'dashboard'])->name('dashboard');
Route::get('user/{user}/verify',[UserController::class,'verify'])->name('user.verify');
Route::get('user/{user}/notification', [NotificationController::class,'index'])->name('user.notification');
Route::get('user/{user}/notification/{notification}', [NotificationController::class,'show'])->name('notification.show');

Route::view('/test', 'pdf.question');

resources/views/dashboard.blade.php
@extends('layouts.base')
@section('title')
    <title>SN - Dashboard</title>
@endsection
@section('content')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ Auth::user()->name }} Dashboard</h1>
    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
            class="fas fa-question-circle mr-1 text-white-50"></i> Make Question</a>
</div>
<div class="row">

    <!-- Question Count Card -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Question Count</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $questions->count() }}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-question fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Answer Count Card -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                            Article Count</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{$articles->count() }}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-newspaper fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Points
                        </div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ Auth::user()->points }}</div>
                            </div>                            
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-uppercase mb-1">
                          <a href="{{ route('user.notification',['user'=> Auth::user()]) }}" class="text-decoration-none text-warning">  Notification</a>
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ Auth::user()->notifications->where('read_status','0')->count() }}</div>
                    </div>
                    <div class="col-auto">
                        <a href="{{ route('user.notification',['user'=> Auth::user()]) }}" class="fas fa-bell fa-2x text-gray-300 text-decoration-none"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.auth')
@section('title')
    <title>SN Home</title>
@endsection
@section('style')
    <style>
        html,
        body {
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            height: 100vh;
            margin: 0;
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        .top-right {
            position: absolute;
            right: 10px;
            top: 18px;
        }

        .content {
            text-align: center;
        }

        .title {
            font-size: 84px;
        }

        .links>a {
            color: #fff;
            padding: 0 25px;
            font-size: 13px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }

    </style>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endsection
@section('js')
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js" defer></script>
@endsection
@section('content')
    <div class="flex-center position-ref full-height">
        @if (Route::has('login'))
            <div class="top-right links">
                @guest
                    <a href="{{ route('login') }}">Login</a>

                    @if (Route::has('register'))
                        <a href="{{ route('register') }}">Register</a>
                    @endif
                @endguest
                @auth
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                @endauth
            </div>
        @endif

        <div class="content">
            <div class="title m-b-md text-white text-bold">
                Stuck Neverflow
            </div>

            <div class="links">
                <a href="{{ route('question.index') }}">Question List</a>
                <a href="{{ route('tag.index') }}">Tag List</a>
                <a href="{{ route('article.index') }}">Article List</a>
                @auth
                    <a href="{{ route('dashboard',['user' => Auth::user()]) }}">Dashboard</a>
                @endauth
            </div>
            <form action="{{ route('tag.search') }}" method="post">
                @csrf
            <div class="row mt-2">                
                    <div class="col-md-2 pt-1">
                        <div class="float-left">
                            <div class="text-white font-weight-bold">
                                <h6>Search Tag</h6>
                            </div>
                        </div>                        
                    </div>
                    <div class="col-md-8">
                        <select class="js-example-basic-single form-control-lg w-100 text-gray-900" id="searchTag" style="height: 100%" name="tag">
                            @foreach ($tags as $tag)
                                <option></option>
                                <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="btn-block btn-success shadow rounded "><i class="fas fa-search"></i></button>
                    </div>                
            </div>
        </form>                
        </div>
    </div>
@endsection
@section('script')
    <script>
        $(document).ready(function() {
            $('#searchTag').select2({
                placeholder: "Search tags",                
            });
        });

    </script>
@endsection