routes/web.php
<?php

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\AnswerController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PDFController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('auth/github', [AuthController::class,'redirectToProvider'])->name('login.github');
Route::get('auth/github/callback', [AuthController::class,'handleProviderCallback']);

Route::resource('question', QuestionController::class);
Route::prefix('question/{question}')->group(function () {
    Route::resource('answer', AnswerController::class, [
        'except' => ['show', 'index']
    ])->middleware('auth');
    Route::post('/answer/{answer}/approve', [AnswerController::class, 'approve'])->name('answer.approve')->middleware('auth');
    Route::put('/answer/{answer}/unapprove', [AnswerController::class, 'unapprove'])->name('answer.unapprove')->middleware('auth');
    Route::post('/generatepdf',[PDFController::class,'question'])->name('question.generatepdf');
});

Route::resource('tag', TagController::class, [
    'only' => ['index', 'store', 'destroy']
]);

Route::get('/tag/{tag}/question',[TagController::class,'question'])->name('tag.question');
Route::get('/tag/{tag}/article',[TagController::class,'article'])->name('tag.article');

Route::get('/', [HomeController::class,'index'] )->name('home');
Route::post('/searchTag',[HomeController::class,'searchTag'])->name('tag.search');


Route::prefix('comment')->group(function () {
    Route::get('{question}/create', [CommentController::class, 'commentQuestionCreate'])->name('commentQuestion.create');
    Route::get('answer/{answer}/create', [CommentController::class, 'commentAnswerCreate'])->name('commentAnswer.create');
    Route::post('{question}', [CommentController::class, 'commentQuestionStore'])->name('commentQuestion.store');
    Route::post('answer/{answer}', [CommentController::class, 'commentAnswerStore'])->name('commentAnswer.store');
    Route::delete('{comment}', [CommentController::class, 'destroy'])->name('comment.destroy');
});

Route::resource('user', UserController::class,[
        
]);
Route::resource('article',ArticleController::class);

Route::prefix('article')->group(function(){
    Route::get('{article}/comment/create',[CommentController::class,'commentArticleCreate'])->name('commentArticle.create');
    Route::post('{article}/comment',[CommentController::class,'commentArticleStore'])->name('commentArticle.store');
});

Route::get('user/{user}/article', [ArticleController::class, 'userArticle'])->name('user.article');
Route::get('user/{user}/dashboard', [UserController::class,'dashboard'])->name('dashboard');
Route::get('user/{user}/verify',[UserController::class,'verify'])->name('user.verify');
Route::get('user/{user}/notification', [NotificationController::class,'index'])->name('user.notification');
Route::get('user/{user}/notification/{notification}', [NotificationController::class,'show'])->name('notification.show');

Route::view('/test', 'pdf.question');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'avatar',
        'provider_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role(){
        return $this->belongsTo(Role::class);
    }

    public function questions(){
        return $this->hasMany(Question::class);
    }

    public function answers(){
        return $this->hasMany(Answer::class);
    }

    public function articles(){
        return $this->hasMany(Article::class);
    }

    public function notifications(){
        return $this->hasMany(Notification::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Models\Question;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Intervention\Image\Facades\Image;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware(['admin'])->except([
            'show','dashboard','edit','update'
        ]);

        $this->middleware(['user'])->only([
            'edit','dashboard','update'
        ]);
    }

    public function index()
    {
        $users = User::all();
        return view('user.index', compact('users'));
    }
    public function create(){
        return view('user.create');
    }

    public function store(Request $request){
        // dd($request);
        $validated = $request->validate([
            'name' => 'required', 'string', 'max:255',
            'email' => 'required', 'string', 'email', 'max:255', 'unique:users',
            'password' => 'required', 'string', 'min:8', 'confirmed',
            'password_confirmation' => 'nullable|min:8|max:12|required_with:password|same:password',
        ]);
        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]);

        return redirect(route('user.index'))->with('toast_success','Account berhasil dibuat');
    }

    public function show(User $user)
    {
        return view('user.show', compact('user'));
    }
    public function edit(User $user)
    {
        return view('user.edit', compact('user'));
    }

    public function update(Request $request, User $user)
    {
        $validated = $request->validate([
            'name' => 'required', 'string', 'max:255',
            'email' => 'required', 'string', 'email', 'max:255', 'unique:users',
            'avatar' => 'mimes:png,jpg,jpeg,gif,svg',
            'current_password' => 'required',
            'new_password' => 'nullable|min:8|max:12|',
            'password_confirmation' => 'nullable|min:8|max:12|required_with:new_password|same:new_password'
        ]);

        // dd($request);
        $user = User::findOrFail(Auth::user()->id);
        if (!is_null($request->input('current_password'))) {
            if (Hash::check($request->input('current_password'), $user->password)) {
                $user->name = $request->input('name');
                $user->email = $request->input('email');
                if ($request->file('avatar')) {
                    $file = $request->file('avatar');
                    $filename = $request->avatar->getClientOriginalName();
                    Image::make($file)->resize(300, 300)->save(public_path('storage/images/avatar/' . $filename));

                    $user->update(['avatar' => $filename]);
                }
                if (!is_null($request->input('new_password'))) {
                    $user->password =  bcrypt($request->input('new_password'));
                }
                $user->save();
                return redirect(route('user.show', ['user' => $user]))->with('toast_success', 'User Berhasil diupdate');
            } else {
                return redirect()->back()->with('toast_danger', 'Password Salah');
            }
        }        
        return redirect()->back()->with('toast_danger', 'User Tidak diupdate');        
    }

    public function dashboard(User $user){
        $questions = Question::all();
        $articles = Article::all();

        return view('dashboard',compact(['questions','articles']));
    }

    public function destroy(User $user){
        User::destroy($user->id);
        return redirect(route('user.index'))->with('toast_success', 'Account berhasil dihapus');
    }

    public function verify(User $user){
        User::where('id',$user->id)->update([
            'email_verified_at' => now()
        ]);
        return redirect(route('user.index'))->with('toast_success','Email account berhasil diverifikasi');
    }
}

resources/views/user/article.blade.php
@extends('layouts.base')
@section('title')
    <title>SN - Article List</title>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-8">
            <div class="float-md-left">
                <h2>Show All Article Made by {{ $user->name }}</h2>
            </div>
        </div>
        <div class="col-md-4">
            @if (Auth::id() == $user->id)
                <div class="float-md-right">
                    <a href="{{ route('article.create') }}" class="btn btn-success"> <i class="fas fa-plus"></i>
                        Create</a>
                </div>
            @endif
        </div>
    </div>
    <hr>
    <div class="card shadow">
        <div class="card-header text-primary font-weight-bold">
            Article List
        </div>
        <div class="card-body">
            <table class="table table-bordered table-responsive-md" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>Thumbnail</td>
                        <td>Title</td>
                        <td>Text</td>
                        <td>Posted at</td>
                        <td>Last updated at</td>
                        <td>Action</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($articles as $article)
                    <tr>
                        <td>{{ $article->id }}</td>
                        <td><img class="img-thumbnail" src="{{ asset('storage/images/thumbnail/300/'.$article->picture) }}" alt="" width="100px" height="auto"></td>
                        <td> <a class="font-weight-bold" href="{{ route('article.show',['article'=>$article]) }}">  {{ $article->title }}</a></td>
                        <td>{!! Str::words($article->content, 15, $end=' ...')   !!}</td>
                        <td>{{ $article->created_at }}</td>
                        <td>{{ $article->updated_at }}</td>
                        <td>
                            <form action="{{ route('article.destroy',['article' =>$article]) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <div class="row">
                                    <div class="col">
                                        <a href="{{ route('article.edit',['article'=> $article]) }}" class="btn btn-block btn-warning my-2">Edit  <i class="fas fa-edit ml-2"></i></a>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-block btn-danger" onclick="return confirm('are you sure want to delete this article?')">Delete<i class="fas fa-trash ml-2"></i></button>
                                    </div>    
                                </div>                                                                
                            </form>
                        </td>
                    </tr>                        
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection
@push('scripts')
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/demo/datatables-demo.js') }}"></script>
@endpush

resources/views/user/create.blade.php
@extends('layouts.base')
@section('title')
    <title>SN - Make Account</title>
@endsection
@section('content')
    <h2>Make User</h2>
    @if ($errors->any())
        <div class="alert alert-danger border-left-danger" role="alert">
            <ul class="pl-4 my-2">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="card">        
        <form action="{{ route('user.store') }}" method="post" autocomplete="off">
            @csrf
        <div class="card-header text-primary font-weight-bold">            
                Fill this form and click the green button to add new user            
        </div>
        <div class="card-body">
            <div class="row mb-4">
                <div class="col-md-6">
                    <label for="name" class="form-label">
                        Name<span class="small text-danger"> *</span>
                    </label>
                    <input type="text" name="name" id="name" class="form-control" required placeholder="Name">
                </div>
                <div class="col-md-6">
                    <label for="name" class="form-label">
                        Role<span class="small text-danger"> *</span>
                    </label>
                    <select name="role" id="role" class="form-control @error('name') is-invalid @enderror">
                        <option value="user">User</option>
                        <option value="admin">Admin</option>
                    </select>
                </div>
            </div>
            <div class="row mb-4">
                <div class="col-md-12">                    
                    <label for="email" class="form-label">
                        Email<span class="small text-danger"> *</span>
                    </label>
                    <input type="email" name="email" id="email" class="form-control @error('email') is-invalid @enderror" required 
                    placeholder="Email" autocomplete="email">
                </div>
            </div>
            <div class="row mb-4">
                <div class="col-md-6">
                    <label for="password" class="form-label">
                        Password<span class="small text-danger"> *</span>
                    </label>
                    <input type="password" name="password" id="password @error('password') is-invalid @enderror " class="form-control" required 
                    placeholder="Password" autocomplete="new-password">
                </div>
                <div class="col">
                    <label for="password_confirmation" class="form-label">
                        Confirm Password<span class="small text-danger"> *</span>
                    </label>
                    <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" required 
                    placeholder="Retype Password" autocomplete="new-password">
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-success float-md-right font-weight-bold">Add new account</button>
                </div>
            </div>            
        </div>
    </form>
    </div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.base')
@section('title')
    <title>Edit Yourr Profile</title>
@endsection
@section('content')
    @if ($errors->any())
        <div class="alert alert-danger border-left-danger" role="alert">
            <ul class="pl-4 my-2">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="card shadow mb-4">

        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Edit ur Account</h6>
        </div>

        <div class="card-body">

            <form method="POST" action="{{ route('user.update', ['user' => Auth::user()]) }}" autocomplete="off" enctype="multipart/form-data">
                @method('PUT')
                @csrf           
                <h6 class="heading-small text-muted mb-4">User information</h6>

                <div class="pl-lg-4">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group focused">
                                <label class="form-control-label" for="name">Name<span
                                        class="small text-danger">*</span></label>
                                <input type="text" id="name" class="form-control" name="name" placeholder="Name"
                                    value="{{ old('name', Auth::user()->name) }}">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group focused">
                                <label for="avatar" class="form-control-label">Profile Pic <span
                                        class="small text-danger">*</span></label>
                                <input type="file" class="form-control-file" name="avatar" id="avatar" accept=".jpeg,.jpg,.png">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label class="form-control-label" for="email">Email address<span
                                        class="small text-danger">*</span></label>
                                <input type="email" id="email" class="form-control" name="email"
                                    placeholder="example@example.com" value="{{ old('email', Auth::user()->email) }}">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group focused">
                                <label class="form-control-label" for="current_password">Current password</label>
                                <input type="password" id="current_password" class="form-control" name="current_password"
                                    placeholder="Current password">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group focused">
                                <label class="form-control-label" for="new_password">New password</label>
                                <input type="password" id="new_password" class="form-control" name="new_password"
                                    placeholder="New password">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group focused">
                                <label class="form-control-label" for="confirm_password">Confirm password</label>
                                <input type="password" id="confirm_password" class="form-control"
                                    name="password_confirmation" placeholder="Confirm password">
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Button -->
                <div class="pl-lg-4">
                    <div class="row">
                        <div class="col text-center">
                            <button type="submit" class="btn btn-primary">Save Changes</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>

    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.base')
@section('title')
    <title>User List</title>
@endsection
@section('css')
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('content')
    <h2>User List</h2>
    <hr>
    <div class="card shadow">
        <div class="card-header text-primary font-weight-bold">
            Data user
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <td>ID</td>
                            <td>Name</td>
                            <td>Email</td>
                            <td>Action</td>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <td>ID</td>
                            <td>Name</td>
                            <td>Email</td>
                            <td>Action</td>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <td>{{ $user->id }}</td>
                                <td><a class="card-link font-weight-bold"
                                        href="{{ route('user.show', ['user' => $user]) }}">{{ $user->name }}</a></td>
                                <td>{{ $user->email }}</td>
                                <td>
                                    <a class="btn btn-circle btn-danger" data-toggle="modal"
                                        data-target="#modal{{ $user->id }}"><i class="fas fa-trash-alt"></i></a>
                                    <div class="modal fade" id="modal{{ $user->id }}" tabindex="-1"
                                        aria-labelledby="modalLabel{{ $user->id }}" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="modalLabel{{ $user->id }}">Account Id :
                                                        {{ $user->id }} </h5>
                                                    <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    Are u sure?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary"
                                                        data-dismiss="modal">Close</button>
                                                    <a class="btn btn-danger"
                                                        href="{{ route('user.destroy', ['user' => $user]) }}"
                                                        onclick="event.preventDefault(); document.getElementById('delete-account{{ $user->id }}').submit();">{{ __('Delete') }}</a>
                                                    <form id="delete-account{{ $user->id }}"
                                                        action="{{ route('user.destroy', ['user' => $user]) }}"
                                                        method="POST" style="display: none;">
                                                        @csrf
                                                        @method('delete')
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    @if ($user->email_verified_at == null)
                                    <a href="{{ route('user.verify',['user'=>$user]) }}" class="btn btn-circle btn-info"><i class="fas fa-check-circle"></i></a>
                                    @endif                                    
                                </td>
                            </tr>
                        @endforeach
                    </tbody>

                </table>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/demo/datatables-demo.js') }}"></script>
@endpush

resources/views/user/notifications.blade.php
@extends('layouts.base')
@section('title')
    <title>User Notification</title>
@endsection
@section('css')
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('content')
    <h2>Notification List</h2>
    <hr>
    <div class="card shadow">
        <div class="card-header text-primary font-weight-bold">
            User Notification
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <td>ID</td>
                            <td>Message</td>                            
                            <td>Type</td>
                            <td>Time</td>
                        </tr>
                    </thead>                    
                    <tbody>
                       @foreach (Auth::user()->notifications as $notification)
                       <tr>
                        <td>{{ $notification->id }}</td>
                           <td> <a class="font-weight-bold" href="{{ route('notification.show',['user' => Auth::user(), 'notification' => $notification ]) }}">{{ $notification->message }}</a></td>                           
                           <td>{{ $notification->type }}</td>
                           <td>{{ $notification->created_at }}</td>
                       </tr>                           
                       @endforeach
                    </tbody>                                     
                </table>
            </div>
        </div>
    </div>    
@endsection
@push('scripts')
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/demo/datatables-demo.js') }}"></script>
@endpush

resources/views/user/show.blade.php
@extends('layouts.base')
@section('title')
    <title>User Detail</title>
@endsection
@section('content')
    <h2>User Detail</h2>
    @if ($errors->any())
        <div class="alert alert-danger border-left-danger" role="alert">
            <ul class="pl-4 my-2">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card shadow">
        <div class="card-header">
            @if (Auth::id() == $user->id)
            <div class="float-right">
                <a href="{{ route('user.edit',['user'=> Auth::user()]) }}" class="btn btn-success"> Edit Profile</a>
                @if (Auth::user()->email_verified_at == null)
                <a href="{{ route('verification.notice') }}" class="btn btn-primary"> Verify</a>
                @endif                
            </div>
            @endif            
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md">
                    <label for="name">Name</label>
                    <h4 class="text-gray-800" name="name">{{ $user->name }}</h4>
                    <label for="name">Email</label>
                    <h4 class="text-gray-800" name="name">{{ $user->email }}</h4>
                    <label for="name">Level</label>
                    <h4 class="text-gray-800" name="name">{{ $user->role->name }}</h4>
                </div>
                <div class="col-md border-left">
                    <div class="row justify-content-md-center">
                        @if ($user->avatar != null)
                        <div class="mb-4 mt-4">
                            <img class="image rounded-circle" src="{{asset('storage/images/avatar/'.$user->avatar)}}" style="width: 150px; height: 150px;" alt="">
                        </div>                 
                        @endif                               
                    </div>
                    <div class="row">
                            <div class="col-md">
                                <h5 class="text-center font-weight-bold">Question Posted</h5>
                            </div>
                            <div class="col-md">
                                <h5 class="text-center font-weight-bold">Answer Posted</h5>                                
                            </div>                                                       
                    </div>
                    <div class="row">
                        <div class="col-md">
                            <p class="text-center" >{{ count($user->questions) }}</p>
                        </div>
                        <div class="col-md">
                            <p class="text-center" >{{ count($user->answers) }}</p>
                        </div>                                                   
                </div>
                </div>                
            </div>            
        </div>
    </div>
    @endsection