routes/web.php
<?php

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\AnswerController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PDFController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('auth/github', [AuthController::class,'redirectToProvider'])->name('login.github');
Route::get('auth/github/callback', [AuthController::class,'handleProviderCallback']);

Route::resource('question', QuestionController::class);
Route::prefix('question/{question}')->group(function () {
    Route::resource('answer', AnswerController::class, [
        'except' => ['show', 'index']
    ])->middleware('auth');
    Route::post('/answer/{answer}/approve', [AnswerController::class, 'approve'])->name('answer.approve')->middleware('auth');
    Route::put('/answer/{answer}/unapprove', [AnswerController::class, 'unapprove'])->name('answer.unapprove')->middleware('auth');
    Route::post('/generatepdf',[PDFController::class,'question'])->name('question.generatepdf');
});

Route::resource('tag', TagController::class, [
    'only' => ['index', 'store', 'destroy']
]);

Route::get('/tag/{tag}/question',[TagController::class,'question'])->name('tag.question');
Route::get('/tag/{tag}/article',[TagController::class,'article'])->name('tag.article');

Route::get('/', [HomeController::class,'index'] )->name('home');
Route::post('/searchTag',[HomeController::class,'searchTag'])->name('tag.search');


Route::prefix('comment')->group(function () {
    Route::get('{question}/create', [CommentController::class, 'commentQuestionCreate'])->name('commentQuestion.create');
    Route::get('answer/{answer}/create', [CommentController::class, 'commentAnswerCreate'])->name('commentAnswer.create');
    Route::post('{question}', [CommentController::class, 'commentQuestionStore'])->name('commentQuestion.store');
    Route::post('answer/{answer}', [CommentController::class, 'commentAnswerStore'])->name('commentAnswer.store');
    Route::delete('{comment}', [CommentController::class, 'destroy'])->name('comment.destroy');
});

Route::resource('user', UserController::class,[
        
]);
Route::resource('article',ArticleController::class);

Route::prefix('article')->group(function(){
    Route::get('{article}/comment/create',[CommentController::class,'commentArticleCreate'])->name('commentArticle.create');
    Route::post('{article}/comment',[CommentController::class,'commentArticleStore'])->name('commentArticle.store');
});

Route::get('user/{user}/article', [ArticleController::class, 'userArticle'])->name('user.article');
Route::get('user/{user}/dashboard', [UserController::class,'dashboard'])->name('dashboard');
Route::get('user/{user}/verify',[UserController::class,'verify'])->name('user.verify');
Route::get('user/{user}/notification', [NotificationController::class,'index'])->name('user.notification');
Route::get('user/{user}/notification/{notification}', [NotificationController::class,'show'])->name('notification.show');

Route::view('/test', 'pdf.question');

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;

    protected $guarded = [];
    public function questions(){
        return $this->belongsToMany(Question::class);
    }

    public function articles(){
        return $this->belongsToMany(Article::class);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth','admin'])->except([
            'index','question','article'
        ]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::orderBy('name','asc')->get();
        return view('tag.index',compact('tags'));
    }
    public function question(Tag $tag)
    {
        return view('tag.question',compact('tag'));
    }
    public function article(Tag $tag)
    {
        return view('tag.article',compact('tag'));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $tag = Tag::firstOrCreate([
            'name' => $request->name,
        ]);
        if ($tag->wasRecentlyCreated) {
            return redirect(route('tag.index'))->with('toast_success',"Tag Berhasil dibuat");
        }else{
            return redirect(route('tag.index'))->with('toast_info',"Tag $tag->name sudah ada");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        // dd($tag);
        Tag::destroy($tag->id);
        return redirect(route('tag.index'))->with('toast_success',"Tag Berhasil dihapus");
    }
}

resources/views/tag/article.blade.php
@extends('layouts.base')
@section('title')
    <title>SN - Tag Article</title>
@endsection
@section('content')
    <h2>{{ $tag->name }} Tag</h2>
    <hr>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {{ Route::is('tag.question') ? 'active' : '' }}" href="{{ route('tag.question',['tag' => $tag]) }}">Question</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {{ Route::is('tag.article') ? 'active' : '' }}" href="{{ route('tag.article',['tag' => $tag]) }}">Article</a>
        </li>
    </ul>
    @foreach ($tag->articles as $article)
    <div class="card my-2">        
        <div class="card-body">            
            <div class="row">
                <div class="col-md-3">
                    <img  class="img-thumbnail" src="{{ asset('storage/images/thumbnail/300/'.$article->picture) }}" alt="">
                </div>
                <div class="col-md-9">
                    <div class="card-title">
                        <div class="text-gray-900">
                            <h5 class="font-weight-bold">{{ $article->title }}</h5>
                        </div>                
                    </div>
                    <div class="card-subtitle">
                        Created at : {{ $article->created_at }}
                    </div>
                    <hr>
                    <div class="card-text">
                        <div class="text-gray-800">
                            {!! Str::words($article->content, 100, $end=' ...') !!}
                        </div>                        
                    </div>
                </div>
            </div>            
        </div>
        <div class="card-footer">
            <div class="float-md-left">
                Creator : <a href="{{ route('user.show',['user'=> $article->user]) }}">{{ $article->user->name }}</a>
            </div>
            <div class="float-md-right">
                <div class="card-link">
                    <a href="{{ route('article.show',['article'=>$article]) }}">Show More</a>
                </div>
            </div>
        </div>
    </div>
    @endforeach
@endsection

resources/views/tag/index.blade.php
@extends('layouts.base')
@section('title')
    <title>SN - Tag List</title>
@endsection
@section('css')
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('content')
    <h2>Display Tag List</h2>
    <hr>
    <form action="{{ route('tag.store') }}" method="POST">
        @csrf
        <div class="row mb-2">
            <div class="col-md-9">
                <input name="name" id="name" type="text" class="form-control"
                    placeholder="Click here to name your new tag then press the button on the right to add your new Tag"
                    autofocus="true" autocomplete="tag">
            </div>
            <div class="col-md-3">
                <button type="submit" class="btn btn-success float-right"> <i class="fas fa-tags"> Create Tag</i></button>
            </div>
        </div>
    </form>
    <div class="card shadow">
        <div class="card-header text-primary font-weight-bold">
            Tag
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-border" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($tags as $tag)
                            <tr>
                                <th scope="row">{{ $loop->iteration }}</th>
                                <td class="text-gray-800 text-lg">{{ $tag->name }}</td>
                                <td>
                                    <form action="{{ route('tag.destroy', ['tag' => $tag]) }}" method="post"
                                        style="inline">
                                        @csrf
                                        @method('delete')
                                        <a href="{{ route('tag.question', ['tag' => $tag]) }}" class="btn btn-info"> <i
                                                class="fas fa-question-circle"></i> Question</a>
                                        <a href="{{ route('tag.article', ['tag' => $tag]) }}" class="btn btn-warning text-dark"> <i
                                                class="fas fa-newspaper"></i> Article</a>
                                        <button type="submit" class="btn btn-danger"
                                            onclick="return confirm('are you sure want to delete this tag?')"> <i
                                                class="fas fa-trash-alt"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/demo/datatables-demo.js') }}"></script>
@endpush

resources/views/tag/question.blade.php
@extends('layouts.base')
@section('title')
    <title>SN - Tag Question</title>
@endsection
@section('content')
    <h2>{{ $tag->name }} Tag</h2>
    <hr>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {{ Route::is('tag.question') ? 'active' : '' }}" href="{{ route('tag.question',['tag' => $tag]) }}">Question</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {{ Route::is('tag.article') ? 'active' : '' }}" href="{{ route('tag.article',['tag' => $tag]) }}">Article</a>
        </li>
    </ul>
    @foreach ($tag->questions as $question)
        <div class="card shadow mb-2">
            <div class="card-header">
                #{{ $question->id }}
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ $question->title }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">Made by: {{ $question->user->name }} on
                    {{ $question->created_at }}</h6>
                <p class="card-text">{!! $question->text !!}</p>
            </div>
            <div class="card-footer">
                <a href="{{ route('question.show', ['question' => $question]) }}" class="card-link">Show Detail</a>
            </div>
        </div>
    @endforeach
@endsection